"""
Django settings for rwanda_film_vault project.

Generated by 'django-admin startproject' using Django 5.2.5.

See https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os

# --- Paths ---
BASE_DIR = Path(__file__).resolve().parent.parent  # Must come first!
GEOIP_PATH = os.path.join(BASE_DIR, "GeoLite2-City.mmdb")  # Use BASE_DIR after defining it

# --- Security ---
SECRET_KEY = 'django-insecure-vvk_6b%u0y*7u=nl0_l!p#hb9bs9)+e36vvfb=98uh9@l&f$u8'
DEBUG = True
ALLOWED_HOSTS = []

# --- Applications ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movies',                   # Your app
    'django.contrib.humanize',  # Human-readable numbers, dates, etc.
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- URL & WSGI ---
ROOT_URLCONF = 'rwanda_film_vault.urls'
WSGI_APPLICATION = 'rwanda_film_vault.wsgi.application'

# --- Templates ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add custom template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --- Database ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rwanda_film_vault_db',
        'USER': 'postgres',  # Make sure your PostgreSQL username
        'PASSWORD': 'Paccy@100',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static Files ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Optional: custom static folder
STATIC_ROOT = BASE_DIR / "staticfiles"   # For production

# --- Default Primary Key Field Type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
