# Generated by Django 5.0.6 on 2025-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
