# Generated by Django 5.0.6 on 2025-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_visitor_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
