# Generated by Django 5.0.6 on 2025-09-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_visitor_lat_visitor_lng'),
    ]

    operations = [
    ]
