# Generated by Django 5.0.6 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_comment_options_comment_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
