# Generated by Django 5.0.6 on 2025-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_comment_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
