# Generated by Django 5.0.6 on 2025-09-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fires',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='green_hearts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='loves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReactionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reaction_type', models.CharField(max_length=20)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'ip_address', 'reaction_type')},
            },
        ),
    ]
