# Generated by Django 5.0.6 on 2025-09-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_fires_movie_green_hearts_movie_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fires',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='green_hearts',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='loves',
        ),
    ]
