# Generated by Django 5.0.6 on 2025-09-12 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_fires_remove_movie_green_hearts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='reactiontracker',
            options={'ordering': ['-reacted_at']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-last_visit']},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddField(
            model_name='movie',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['uploaded_at'], name='movies_movi_uploade_79fa26_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_visit'], name='movies_visi_last_vi_ecf86c_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['last_seen'], name='movies_watc_last_se_440abb_idx'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['downloaded_at'], name='movies_down_downloa_79f1dc_idx'),
        ),
    ]
