# Generated by Django 5.0.6 on 2025-09-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_downloadhistory_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reactiontracker',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('fire', 'Fire')], max_length=20),
        ),
    ]
