# Generated by Django 5.0.6 on 2025-09-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
