# Generated by Django 5.0.6 on 2025-10-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReactionTracker',
        ),
    ]
