# Generated by Django 5.0.6 on 2025-10-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_delete_reactiontracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
