# Generated by Django 5.2.7 on 2025-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='converted_video',
            field=models.FileField(blank=True, null=True, upload_to='converted_movies/'),
        ),
    ]
